Repository UdL-EPS-SoftArch/myapartments, pull requests merged in 2025-01, with the labels that each got.

#63 Fix room creation usability aberration
  src/app/apartment/apartment-create/apartment-create.component.ts
  src/app/room/room-create/room-create.component.html
  src/app/room/room-list/room-list.component.html
  src/app/room/room-list/room-list.component.ts
  src/app/room/room-update/room-update.component.html
  src/index.html
Labels: bug

#72 Create e2e test delete apartment
  cypress.config.ts
  e2e/features/Apartments/DeleteApartment.feature
  e2e/steps/Apartments/delete-apartment.ts
  src/app/apartment/apartment-list/apartment-list.component.html
Labels: test

#80 Feature create advertisement
  e2e/features/Advertisement/CreateAdvertisement.feature
  e2e/steps/Advertisement/create-advertisement.ts
  src/app/advertisement/create-advertisement/create-advertisement.component.html
Labels: enhancement, test

#86 75 delete adevertaisment test
  e2e/features/Advertisement/DeleteAdvertisement.feature
  e2e/steps/Advertisement/delete-advertisement.ts
  src/app/advertisement/advertisement-delete/advertisement-delete.component.html
  src/app/advertisement/advertisment-list/advertisement-list.component.html
  src/app/advertisement/advertisment-list/advertisement-list.component.ts
  src/app/advertisement/create-advertisement/create-advertisement.component.ts
Labels: bug, test

#89 87 create documentation section
  .hintrc
  src/app/about/about.component.html
  src/app/app-routing.module.ts
  src/app/documentation/documentation.component.css
  src/app/documentation/documentation.component.html
  src/app/documentation/documentation.component.ts
  src/app/navbar/navbar.component.html
  src/app/navbar/navbar.component.ts
  src/assets/images/advertisements.png
  src/assets/images/apartments.png
  src/assets/images/documentation.png
  src/assets/images/rooms.png
Labels: documentation, enhancement
